# Site settings
title: "Tamado Ramot Sitohang"
email: "hello@ramottamado.dev"
author: "Tamado Ramot Sitohang"
url: "https://tamado.codes"
description: "Data engineering and analytics"

# Theme
nadya:
  disable_social: true
  disable_attribution: true

# Giscus
# giscus:
#   repo: "ramottamado/ramottamado.github.io"
#   repo_id: "R_kgDOG0sN9g"
#   category: "Announcements"
#   category_id: "DIC_kwDOG0sN9s4CBNAW"
#   mapping: "og:title"
#   reactions: 1
#   input: "bottom"

# Default
defaults:
  - scope:
      path: "_posts"
    values:
      twitter:
        card: summary_large_image

# Layout
nav_pages:
  - categories.md
  - about.md

# Logo
favicon: "favicon.svg"
logo: "favicon.svg"
icon: "favicon.png"
alt_icon: "favicon.ico"

# SEO
# google_site_verification: ""
gravatar: d380135b4724b6b8e74bd9f41b978284
github:
  username: ramottamado
twitter:
  card: summary
facebook:
  publisher: 103250301049786
  author: 100000091609630

# Plugin
sitemap:
  changefreq: monthly
feed:
  excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
remote_theme: ramottamado/nadya
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
