# Site settings
title: "Tamado Ramot Sitohang"
email: "hello@ramottamado.dev"
author: "Tamado Ramot Sitohang"
url: "https://ramottamado.dev"
tagline: "Big data engineering and analytics"
description: >- # this means to ignore newlines and trim last newline
  Tamado Ramot Sitohang's blog.<br />
  Made with ❤️.

# Theme
nadya:
  disable_social: true
  disable_attribution: true

# Default
defaults:
  - scope:
      path: "_posts"
    values:
      twitter:
        card: summary_large_image

# Layout
nav_pages:
  - categories.md
  - about.md

# Logo
favicon: "favicon.svg"
logo: "favicon.svg"
icon: "favicon.png"
alt_icon: "favicon.ico"

# SEO
google_site_verification: "zaJj36ddah20RkBG1RrQqWm-IlXepNuw8ch6SYXeBPQ"
gravatar: d380135b4724b6b8e74bd9f41b978284
github:
  username: "ramottamado"
# instagram:
#   username: ""
# linkedin:
#   username: "ramottamado"
twitter:
  card: summary
  username: "theramottamado"
facebook:
  publisher: 103250301049786
  author: 100000091609630
social:
  name: "Tamado Ramot Sitohang"
  links:
    - "https://ramottamado.dev"
    - "https://twitter.com/theramottamado"

# Plugin
sitemap:
  changefreq: monthly
feed:
  excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html

remote_theme: ramottamado/nadya@v0.1.7

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
